"""Add game_tag table

Revision ID: 6eee6587a1dc
Revises: 35798de6c516
Create Date: 2023-09-06 02:30:37.217413

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6eee6587a1dc"
down_revision = "35798de6c516"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_tag",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "timeline_post",
        sa.Column("game_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
    )
    op.drop_column("timeline_post", "game_tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "timeline_post",
        sa.Column(
            "game_tags",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("timeline_post", "game_ids")
    op.drop_table("game_tag")
    # ### end Alembic commands ###
