import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import Providers from './providers';

const notoSansJapanese = Noto_Sans_JP({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang="ja" suppressHydrationWarning>
    <body className={`${notoSansJapanese.className}`}>
      <Providers>{children}</Providers>
    </body>
  </html>
);

export default RootLayout;
